install: # установить зависимости
	poetry install

build: # сборка
	poetry build


run: # выполнить
	poetry run brain-games

publish:
	poetry publish --dry-run.

package-install:
	 python3 -m pip install --user /home/pavel/python-project-lvl1/dist/*.whl
